#taking a base image from docker images,as build because it is a two
#stage build
FROM node:18 as build 
#setting the working directory
WORKDIR /app
#copying the package.json file to the working directory
COPY  package.json ./ 
#installing the dependencies
RUN npm install 
#copying the rest of the files to the working directory
COPY  . .  
RUN npm run build
#use nginx to serve the React app

#taking a base image from docker images
FROM nginx:alpine
#copying the built react image from the previous state to the default 
#nginx directory --from=build is used to specify the previous build state
COPY --from=build /app/build /usr/share/nginx/html

#copying the nginx configuration file to the default nginx directory
COPY default.conf /etc/nginx/conf.d/default.conf
#explosing port number 80 for communication
EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]

CMD sleep 10 && nginx -g "daemon off;"

